---
title: "Classifying Guardian News Articles Using Naive Bayes"
layout: post
date: "2015-11-23T12:54:00"
categories: ["tutorial"]
tags: ["Python", "Naive Bayes", "R", "Text analysis"]
blog: true
author: Jasper Ginn
description: Classifying text documents is a fairly straightforward task which is fun to do, and so I wanted to test it out by classifying articles from the belonging to four categories
---

A while back, I adapted the <a href="https://en.wikipedia.org/wiki/Naive_Bayes_classifier">Naive Bayes</a> model used in <a href="https://www.youtube.com/watch?v=j3IGd5CjsVA">this excellent video</a> to classify text documents in Python. Classifying text documents is a fairly straightforward task which is fun to do, and so I wanted to test it out by classifying articles from the <a href="http://www.theguardian.com">Guardian</a> belonging to four categories. In the rest of this post, I'm going to outline some theory on probabilities and <em>Bayes' Law</em>. Then, we'll pre-process the Guardian news articles and attempt to classify as many of them to the correct section.
<h2>Probabilities and Bayes' law</h2>
In order to properly understand Bayes' theorem, we need to wrap our heads around conditional probabilities. I will first go over an example where the probabilities are independent.

Suppose that we throw a die. The probability of getting any number is <span>$\frac{1}{6}$</span> as there are 6 numbers on the die which all have an equal probability of showing up. Now suppose we throw the same die twice. The probability of, say, getting a value of <span>6</span> on both throws is <span>$P(x,y) = \frac{1}{6} \times \frac{1}{6} = \frac{1}{36}$</span>. The reason we are allowed to calculate the joint probability of x and y is because these events are <a href="https://www.mathsisfun.com/data/probability-events-independent.html">independent</a>. That is, the result of the first throw will not affect the result of the second throw, and we can calculate the joint probability by using <span>$P(x, y) = P(x) P(y)$</span>.

<a href="http://www.mathgoodies.com/lessons/vol6/conditional.html">Conditional probabilities</a> concern events that are not independent of one another. Simply put, the conditional probability of an event x occurring is the probability that x will occur <em>given</em> that we already know some other event, y, has occurred. For events that are not independent, we can calculate the probability that both events happened by using:

$$
P(x, y) = P(x) P(x|y)
$$

We can then get to conditional probabilities by dividing this formula by <span>$P(x)$</span> such that we get

<span>$$P(x|y) = \frac{P(x, y)}{P(x)}$$</span>.

How does all of this relate to <a href="https://en.wikipedia.org/wiki/Bayes%27_theorem">Bayes' Law</a>? Well, the cool thing about Bayes' law is that it offers us a way to estimate <span>$P(x|y)$</span> <em>given</em> that we have empirical data on <span>$P(y|x)$</span>. Consider the convenience of this approach through the following (archetypical) example. Suppose that we want to build a spam filter for an e-mail client. In this case, we have two classes: <em>spam</em> and <em>not spam</em> (or <em>'ham'</em>, as it is often referred to in text books). We want to classify each incoming email as either one of these classes by looking closely at each word used in the email. The probability that we are interested in is <span>$P(word|spam)$</span>, or <em>"what is the probability of this word occurring in an email given that this email is spam"</em>.

The problem with this approach is that, in order for this to work properly, we need data on <em>all</em> spam and non-spam emails. Clearly, this is infeasible. Bayes' law offers us a way to turn the logic around, such that it allows us to predict <span>$P(y|x)$</span>, or "what is the probability of this email being spam, <em>given that I know that it contains this word</em>". The goal is to take these probabilities and extrapolate them to new data.

If we return to the section above on conditional probabilities for a moment, we can deduce that there is a relationship between the joint probabilities of events x and y <span>$P(x, y)$</span> and the conditional probabilities <span>$P(x|y)$</span> and <span>$P(y|x)$</span>, such that:

<span>$P(x|y) P(y) = P(x, y) = P(y|x) P(x)$</span>.

Assuming that <span>$P(x) \neq 0$</span>, we solve for <span>$P(y|x)$</span> to get to Bayes' Law

<span>$$P(y|x) = \frac{P(x|y) P(y)}{P(x)}$$</span>

In the formula above, the left-hand side is referred to as the <em>posterior probability</em>. This is the probability that an observation belongs to class <span>$C_i$</span> given a number of classes. On the right side of the equation, <span>$P(x|y)$</span> is referred to as the <em>likelihood</em> of an observation belonging to a class <span>$C_i$</span>. The likelihood is usually estimated as some <a href="https://en.wikipedia.org/wiki/Probability_density_function">density function</a> that conveys how "likely" it is for a given observation to belong to a class.

<span>$P(y)$</span> and <span>$P(x)$</span> are referred to as <em>'priors'</em>. Essentially, priors can be treated as prior beliefs about the data, and 'weight' the data according to some belief we hold about their distribution. In the context of the Naive Bayes approach (see below), <span>$P(y)$</span> is the probability of seeing a randomly chosen observation belonging to the <span>$C_{th}$</span> class. So if we have a dataset with 50.000 observations of which 10.000 belong to class <span>$C_1$</span> and 40.000 observations belong to class <span>$C_2$</span>, the priors are <span>$(0.20, 0.80)$</span>. <span>$P(x)$</span> is regarded as a 'scaling factor'.

<h2>From Bayes' law to the Naive Bayes Algorithm</h2>

Given a modeling problem, there are many ways to estimate the different elements of Bayes' law. <a href="https://en.wikipedia.org/wiki/Naive_Bayes_classifier">Naive Bayes</a> is often used for high-dimensional datasets. This makes Naive Bayes applicable for a wide variety of problems, such as <a href="https://en.wikipedia.org/wiki/Naive_Bayes_spam_filtering">spam filters</a>.

Naive Bayes is called 'naive' because it treats each of its inputs as <em>independent</em>. Especially in the case of text data, this is an erroneous assumption, as textual features are often tied to one another in various ways. Nonetheless, the Naive Bayes classifier usually achieves very good results on text data (as we will see).

In the context of a <a href="https://en.wikipedia.org/wiki/Naive_Bayes_classifier#Multinomial_naive_Bayes">multinomial Naive Bayes model</a> using a <a href="https://en.wikipedia.org/wiki/Bag-of-words_model">bag-of-words</a> approach,[^1] the <em>priors</em> are defined as the number of observations in each class (<span>$P(y)$</span> in the formula above) and the number of observations for each word over <em>all</em> classes (<span>$P(x)$</span> in the formula above). The <em>likelihood</em> is defined as the number of times a word occurs in each class.

As an example, consider the following five documents:

<table class="generic">
<thead>
<tr class="generic">
<th class="generic">Document</th>
<th class="generic">w1</th>
<th class="generic">w2</th>
<th class="generic">w3</th>
<th class="generic">section</th>
</tr>
</thead>
<tbody>
<tr class="generic">
<td class="generic">doc1</td>
<td class="generic">trump</td>
<td class="generic">running</td>
<td class="generic">president</td>
<td class="generic">national</td>
</tr>
<tr class="generic">
<td class="generic">doc2</td>
<td class="generic">abe</td>
<td class="generic">army</td>
<td class="generic">japan</td>
<td class="generic">world</td>
</tr>
<tr class="generic">
<td class="generic">doc3</td>
<td class="generic">trump</td>
<td class="generic">japan</td>
<td class="generic">army</td>
<td class="generic">national</td>
</tr>
<tr class="generic">
<td class="generic">doc4</td>
<td class="generic">china</td>
<td class="generic">trump</td>
<td class="generic">president</td>
<td class="generic">national</td>
</tr>
<tr class="generic">
<td class="generic">test</td>
<td class="generic">trump</td>
<td class="generic">china</td>
<td class="generic">army</td>
<td class="generic">???</td>
</tr>
</tbody>
</table>

We want to calculate the section of the fifth document (the 'test' observation) by using documents one to four. The prior probabilities are <span>$P(World) = 0.25$</span> and <span>$P(National) = 0.75$</span>. The likelihood for each word given its class is:

<table class="generic">
<thead>
<tr class="generic">
<th class="generic">Word_section</th>
<th class="generic">Likelihood</th>
</tr>
</thead>
<tbody>
<tr class="generic">
<td class="generic">trump_national</td>
<td class="generic">0.3333333</td>
</tr>
<tr>
<td class="generic">running_national</td>
<td class="generic">0.1111111</td>
</tr>
<tr>
<td class="generic">president_national</td>
<td class="generic">0.2222222</td>
</tr>
<tr>
<td class="generic">abe_national</td>
<td class="generic">0.0000010</td>
</tr>
<tr>
<td class="generic">japan_national</td>
<td class="generic">0.1111111</td>
</tr>
<tr>
<td class="generic">army_national</td>
<td class="generic">0.1111111</td>
</tr>
<tr>
<td class="generic">china_national</td>
<td class="generic">0.1111111</td>
</tr>
<tr>
<td class="generic">china_world</td>
<td class="generic">0.0000010</td>
</tr>
<tr>
<td class="generic">trump_world</td>
<td class="generic">0.0000010</td>
</tr>
<tr>
<td class="generic">running_world</td>
<td class="generic">0.0000010</td>
</tr>
<tr>
<td class="generic">president_world</td>
<td class="generic">0.0000010</td>
</tr>
<tr>
<td class="generic">abe_world</td>
<td class="generic">0.3333333</td>
</tr>
<tr>
<td class="generic">army_world</td>
<td class="generic">0.3333333</td>
</tr>
<tr>
<td class="generic">japan_world</td>
<td class="generic">0.3333333</td>
</tr>
</tbody>
</table>

We can now calculate the posterior probability for both sections by using:

<span>$p(class|document) = \frac{p(class) p(trump|c) p(china|c) p(army|c)}{p(words)}$</span>

Given the words we see in document five, we calculate the probability that the documents belongs to each class, which amounts to <span>$P(World) = 2.78E-14$</span> and <span>$P(National) = 0.00103$</span>. We then determine for which class the <em>posterior probability</em> is <a href="https://en.wikipedia.org/wiki/Maximum_likelihood">maximized</a>, and that is the class to which we assign the document. In this case, we would assign document five to the class 'National'.

As the denominator is the same for all classes in the formula above, it is common to leave it out and to calculate the log-odds of the data by taking the log of both sides. This also means that instead of multiplying the probabilities, we will be simply calculating the sum of the log-odds. To ensure we never take the log of zero, we add a 'smoother' (usually a small number).
<h2>The data</h2>
As an example of how Naive Bayes works, we will now classify 5.966 articles belonging to four sections of the Guardian. The data we will be using for classification is scraped using the <a href="http://open-platform.theguardian.com/">Guardian API</a>. You can find the script to download articles on <a href="https://github.com/JasperHG90/naiveBayes-guardian-articles/blob/master/guardian_download.R" target="_blank">GitHub</a>. The goal is to correctly classify as many articles to their category by using the article title and body.

<table class="generic">
 <thead>
  <tr class="generic">
   <th class="generic"> Section </th>
   <th class="generic"> Number.obs </th>
   <th class="generic"> Proportion </th>
  </tr>
 </thead>
<tbody>
  <tr class="generic">
   <td class="generic"> Politics </td>
   <td class="generic"> 1493 </td>
   <td class="generic"> 0.250 </td>
  </tr>
  <tr class="generic">
   <td class="generic"> Sport </td>
   <td class="generic"> 1504 </td>
   <td class="generic"> 0.252 </td>
  </tr>
  <tr class="generic">
   <td class="generic"> Travel </td>
   <td class="generic"> 1472 </td>
   <td class="generic"> 0.247 </td>
  </tr>
  <tr class="generic">
   <td class="generic"> World news </td>
   <td class="generic"> 1497 </td>
   <td class="generic"> 0.251 </td>
  </tr>
</tbody>
</table>

The data is split into a training set (90%), and a test set (10%) to evaluate the performance of the classifier.
<h2>Pre-processing: cleaning text data</h2>
There is an <a href="http://nlp.stanford.edu/">entire field</a> dedicated to the use of text as data. In this context, our pre-processing steps are relatively easy:

1. Clean data - remove whitespaces, punctuation, numbers etc.
2. Remove stopwords - remove words like for, if, and etc.
3. Stem data - try to find as many overlap between different variations of words.
4. Feature selection - avoid overfitting by selecting <em>most important</em> features.

<h3>Cleaning data, removing stopwords and stemming</h3>
With text analysis, we try to remove as much 'noise' as we can from the data. This means that words like <code>play.</code> and <code>Played</code> should (in the general case) be counted as the same word. However, <code>play.</code> contains a period and <code>Played</code> contains a capital letter. As such, they will be treated as separate words. By <strong>cleaning</strong> text, we can remove punctuation, capitals, numbers and whitespaces such that we get <code>play</code> and <code>played</code>.

Although cleaning text will improve our features a lot, the words <code>play</code> and <code>played</code> will still be categorized as different words. In order to get around this problem, we <strong>stem</strong> data. <a href="https://en.wikipedia.org/wiki/Stemming">Stemming</a> attempts to capture the 'root' of each word, such that e.g. 'love' and 'loved' both become 'lov'. An alternative approach to stemming is to 'lemmatize' the data. <a href="http://nlp.stanford.edu/IR-book/html/htmledition/stemming-and-lemmatization-1.html">Lemmatization</a> tries to determine the <a href="http://nlp.stanford.edu/software/tagger.shtml">'position-of-speech'</a> of each word in a sentence. Using the information on the word position, lemmatization can then determine the proper base of the word.

Let's consider an example where we clean a sentence, remove stopwords and stem the text:

<em>"The president said voters should keep pressure on members of Congress to reach across party lines and ensure initiatives in his budget are enacted"</em>

First, we <strong>clean</strong> the text of capital letters, punctuation and <strong>remove stopwords</strong>. This gives us:

<em>"president said voters keep pressure members congress reach across party lines ensure initiatives budget enacted"</em>

Next, we <strong>stem</strong> the text:

<em>"presid said voter keep pressur member congress reach across parti line ensur initi budget enact"</em>

Note that if we use POS tags, we don't need to remove stopwords. Nor do we need to convert capital letters. Doing so would remove a lot of valuable information (e.g. the difference between "Bill" and "bill"). We can always filter a sentence for POS tags that aren't nouns or verbs, and apply stopword removal after lemmatizing the text to filter out common words like 'be':

<em>"The-DT president-NN said-VBD voters-NNS should-MD keep-VB pressure-NN on-IN members-NNS of-IN Congress-NNP to-TO reach-VB across-RP party-NN lines-NNS and-CC ensure-NN initiatives-NNS in-IN his-PRP$budget-NN are-VBP enacted-VBN"</em>

If we then lemmatize this sentence, we end up with:

<em>"The president say voter should keep pressure on member of Congress to reach across party line and ensure initiative in his budget be enact"</em>

Or, if we choose to keep only nouns, verbs and remove stopwords, we get:

<em>"president say voter keep pressure member Congress reach party line ensure initiative budget enact"</em>

The choice between stemming and lemmatizing can be computational. Stemming is resource-friendly, while lemmatizing can be computationally intensive. This choice is further informed by the modeling technique. Recall that Naive Bayes treats all features as independent. As such, taking things like POS into account may not help much in providing higher accuracy, since the model doesn't take this information into account. Models like <a href="http://nlp.stanford.edu/IR-book/html/htmledition/support-vector-machines-and-machine-learning-on-documents-1.html">Support Vector Machines</a>, on the other hand, are better suited to process this information.
<h3>Feature selection</h3>
When working with text data (like any other high-dimensional data), it is a good idea to remove sparse features (or <em>variables</em>). These are features which don't add a lot of new information to the model, and may lead to <a href="https://en.wikipedia.org/wiki/Overfitting" target="_blank">overfitting</a>. As an example, consider taking 20.000 news articles from the New York Times API and 4.000 articles from the Guardian API. Your goal is to train a model on the NYT articles and predict one of four categories of the Guardian articles. If you use <em>all</em> features that are present in the NYT articles, you end up with a lot of noise that may not be useful - or could be counter-informative - when predicting the section of the Guardian articles.

There are several ways to perform feature selection. A common method is to look at term frequency, establish a threshold (common values are 5 or 10), and remove all features that fall below that threshold. An extension of this approach is <a href="http://nlp.stanford.edu/IR-book/html/htmledition/tf-idf-weighting-1.html">term-frequency inverse document frequency</a>.

One method that is very applicable to the 'bag-of-words' approach is to perform a <a href="https://en.wikipedia.org/wiki/Chi-squared_test">chi-squared test</a>. In essence, the chi-square test is a non-parametric test of independence for categorical data. In the context of text data, the <a href="http://nlp.stanford.edu/IR-book/html/htmledition/feature-selectionchi2-feature-selection-1.html">chi-squared test</a> is used to determine whether the occurrence of a word in a category differs from the total number of occurrences of that word. We then assign a score to each word, rank them in order of this score, and establish a cut-off point for the number of words we want to include in determining our classification.

When we look at the ten most informative words in the Guardian dataset, we get the following:

<table class="generic">
<thead>
<tr class="generic">
<th class="generic">Word</th>
<th class="generic">Score</th>
</tr>
</thead>
<tbody>
<tr class="generic">
<td class="generic">leader</td>
<td class="generic">3203102.22</td>
</tr>
<tr class="generic">
<td class="generic">cameron</td>
<td class="generic">443533.02</td>
</tr>
<tr class="generic">
<td class="generic">minist</td>
<td class="generic">259265.63</td>
</tr>
<tr class="generic">
<td class="generic">world</td>
<td class="generic">242961.40</td>
</tr>
<tr class="generic">
<td class="generic">win</td>
<td class="generic">50576.13</td>
</tr>
<tr class="generic">
<td class="generic">england</td>
<td class="generic">49697.83</td>
</tr>
<tr class="generic">
<td class="generic">game</td>
<td class="generic">39441.80</td>
</tr>
<tr class="generic">
<td class="generic">tori</td>
<td class="generic">36113.20</td>
</tr>
<tr class="generic">
<td class="generic">polit</td>
<td class="generic">27203.11</td>
</tr>
<tr class="generic">
<td class="generic">support</td>
<td class="generic">25723.21</td>
</tr>
</tbody>
</table>

These make sense. The words <code>leader</code> and <code>world</code> are likely connected to the section <code>world news</code>. The words <code>cameron</code>, <code>minist</code>, <code>tori</code> and <code>polit</code> likely occur in the section <code>politics</code> and so on.

<h2>Classifying the Guardian Articles using Naive Bayes</h2>

Now we're ready for the fun part! We'll be classifying the Guardian articles using <a href="https://github.com/JasperHG90/naiveBayes-guardian-articles/blob/master/naiveBayes.py" target="_blank">this script</a> that I adapted from <a href="https://www.youtube.com/watch?v=j3IGd5CjsVA">this video</a>.[^2] Of course, you can also use an out-of-the-box model from e.g. the <a href="http://scikit-learn.org/stable/modules/naive_bayes.html">sklearn python module</a>, but using a custom script helps to better understand what's going on under the hood.

Firstly, it is important to consider what we need to do 'better' than. That is, if we picked a random label for each observation, what would our accuracy be? Secondly, we need to consider what our expected accuracy will be if we simply assigned the label of the largest group to each observation. The accuracy rates for these models would 25% and 33% respectively, so these are the models we aim to outperform.

The data for our model will be pre-processed by removing numbers, punctuation and stopwords from the text, after which the porter stemmer is applied to stem the words. We will evaluate model performance using <a href="https://en.wikipedia.org/wiki/Cross-validation_(statistics)">k-fold cross-validation</a> with <span>$k=5$</span> and testing the model on the test set.

The results from the k-fold validation results in an average accuracy of 95.5%. Likewise, the model results in an overall accuracy of <95.3% on the test set. The high concordance between these two figures indicates that, despite the simplicity of the model, it correctly classifies roughly 95% of the unseen articles in the test set. As such, we are vastly outperforming the base models of 25% and 33%.

Although accuracy gives us a good overall metric of how well the model is doing, it is important to look at the performance per class. This is shown in the <a href="https://en.wikipedia.org/wiki/Confusion_matrix">confusion matrix</a> below.

<table class="generic">
<thead>
<tr class="generic">
<th class="generic"></th>
<th class="generic">Politics</th>
<th class="generic">Sport</th>
<th class="generic">Travel</th>
<th class="generic">World news</th>
</tr>
</thead>
<tbody>
<tr class="generic">
<td class="generic">Politics</td>
<td class="generic">140</td>
<td class="generic">0</td>
<td class="generic">1</td>
<td class="generic">8</td>
</tr>
<tr class="generic">
<td class="generic">Sport</td>
<td class="generic">2</td>
<td class="generic">145</td>
<td class="generic">1</td>
<td class="generic">2</td>
</tr>
<tr class="generic">
<td class="generic">Travel</td>
<td class="generic">1</td>
<td class="generic">0</td>
<td class="generic">141</td>
<td class="generic">5</td>
</tr>
<tr class="generic">
<td class="generic">World news</td>
<td class="generic">1</td>
<td class="generic">0</td>
<td class="generic">7</td>
<td class="generic">142</td>
</tr>
</tbody>
</table>
Here, it becomes clear that the <code>Travel</code> and <code>World news</code> classes contain higher false positives than the other classes. Overall, these results make sense. While a section like <code>Sport</code> is separated well from the other sections, the <code>world_news</code> section is less clearly bounded, and often contains news on international politics.

<h1>Conclusion</h1>

In this post, we looked at an implementation of the Naive Bayes algorithm to classify news articles from the Guardian. Even though Naive Bayes is a simple approach to such a problem, it performs very well on the Guardian dataset. We could improve on this result by looking at e.g. different word combinations using <a href="https://en.wikipedia.org/wiki/N-gram">n-grams</a>, by using a different stemming technique, by fine-tuning parameters like the number of features we include in the model or the smoother with use in the Naive Bayes model, or by choosing a more sophisticated model. Further information on Bayes' law and Naive Bayes can be found in the references list below.

<h1>Further reading</h1>
<ul>
<li>Schutt, Rachel, and Cathy O'Neil. Doing data science: Straight talk from the frontline. " O'Reilly Media, Inc.", 2013. pp. 98-104</li>
<li>James, Gareth, et al. An introduction to statistical learning. New York: springer, 2013. pp. 138-142</li>
<li>Zumel, Nina, John Mount, and Jim Porzak. Practical data science with R. Manning, 2014. pp. 134-138</li>
<li>Machine Learning (Part 3 of 5): Naive Bayes Classifier. URL: https://www.youtube.com/watch?v=j3IGd5CjsVA</li>
<li>Multinomial Naive Bayes: A worked example. URL: https://class.coursera.org/nlp/lecture/28</li>
</ul>

<h1>Notes</h1>

[^1]: Multinomial naive bayes classifiers differ from multivariate naive bayes classifiers in the sense that they take a different input. That is, multivariate models take <em>binary</em> features, whereas multinomial models take <em>term frequencies</em> as features. For more information, see <a href="http://sebastianraschka.com/PDFs/articles/naive_bayes_1.pdf">this helpful overview</a>
[^2]: I highly recommend that you watch this video. It gives one of the best explanations of Naive Bayes that I have come across
